matrix:
  include:
      os: linux
      arch: s390x
      language: generic

services: docker

install: skip
script:
  - echo $TRAVIS_ARCH
  - echo $TRAVIS_BRANCH
  - docker build -t testimage -f Dockerfile .
